##############################################################################
#
# hw0 Makefile
#
# Makes (and cleans) every subdirectory of hw0
#
# Tim Menninger
#
##############################################################################

all:
	cd Part1;make
	cd Part2;make
	cd Part3;make
	cd Part4;make

clean:
	cd Part1;make clean
	cd Part2;make clean
	cd Part3;make clean
	cd Part4;make clean
